version: '3.7'
services:
  symfony:
    container_name: symfony
    build:
      context: .docker/symfony
      args:
        TIMEZONE: 'Europe/Paris'
        GIT_USER_EMAIL: 'cyberalternative@gmail.com'
        GIT_USER_NAME: 'Michael Gonzalez'
    volumes:
      - ./:/var/www/symfony
    networks:
      - symfony
  nginx:
    container_name: nginx
    build:
      context: .docker/nginx
    volumes:
      - ./:/var/www/symfony
    env_file:
      - .docker/.env.nginx
    ports:
      - 8000:80
    networks:
      - symfony
networks:
  symfony: